title: Stanley Lam # your name (or website title) here
logo: "/images/download (3).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Aspiring data analyst with a solid command of a wide range of analytical tools and techniques. 
  <br><br>
   Proficient in Python (pandas, numpy, matplotlib, seaborn) for complex data analysis and visualization, Tableau and Power BI (including DAX and report creation) for insightful data presentations, RStudio (ggplot2, dplyr) for statistical analysis, and SQL for efficient querying. Skilled in PySpark for big data processing and Excel (Solver, Goal Seek, Pivot Tables, Vlookup, Conditional Formatting) for data manipulation and modeling.
  <br><br>
  <a href="https://www.linkedin.com/in/stanleylam24/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
